name: Deploy Docs

on:
  push:
    branches: [ main ]
    paths: 
      - "src/docs/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm run bootstrap
      - run: cd src/docs
      - run: npm run deploy space-kit.surge.sh --token ${{ secrets.SURGE_TOKEN }} 
